"""Order and item created date

Revision ID: 01d885ba3463
Revises: 67d807c41ca5
Create Date: 2021-03-16 14:20:39.526764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '01d885ba3463'
down_revision = '67d807c41ca5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('item_created_date', sa.DateTime(), nullable=True))
    op.drop_column('item', 'date')
    op.add_column('order', sa.Column('order_created_date', sa.DateTime(), nullable=True))
    op.drop_column('order', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('order', 'order_created_date')
    op.add_column('item', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('item', 'item_created_date')
    # ### end Alembic commands ###
