"""Add column last_name to User model

Revision ID: 0743a08f5f96
Revises: edd656a73fd4
Create Date: 2021-03-15 10:14:09.240073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0743a08f5f96'
down_revision = 'edd656a73fd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
