"""Add column last_name to User model

Revision ID: 4338a7f9022e
Revises: d4ecf7aeb5ea
Create Date: 2021-03-15 10:05:47.720582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4338a7f9022e'
down_revision = 'd4ecf7aeb5ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
