"""Add Bill model

Revision ID: 53184e4cfe8e
Revises: 6cce493906a2
Create Date: 2021-03-16 12:52:43.256358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53184e4cfe8e'
down_revision = '6cce493906a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
