"""Add col new_price

Revision ID: 6cce493906a2
Revises: fbca71d989da
Create Date: 2021-03-16 08:24:41.441590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cce493906a2'
down_revision = 'fbca71d989da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('new_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'new_price')
    # ### end Alembic commands ###
