"""Add column last_name to User model

Revision ID: 7a0dd1878a0e
Revises: 4338a7f9022e
Create Date: 2021-03-15 10:07:30.980953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a0dd1878a0e'
down_revision = '4338a7f9022e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
