"""Add column last_name to User model

Revision ID: edd656a73fd4
Revises: 7a0dd1878a0e
Create Date: 2021-03-15 10:11:11.024888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edd656a73fd4'
down_revision = '7a0dd1878a0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
